### PR TITLE
Class name mixin

### PR DESCRIPTION
**Pull request by rsahlstrom**
# Creates ClassNameMixin

Creates a Mixin that makes it easy to add ClassName as a prop to add
additional class names to a React Component.

Adds a simple example page to show how it works.
# Adds Tests Using Mocha

Uses Mocha and JSDom to write tests for the mixin to ensure that
getCombinedClassNames and convertStringToClassSetObject is working
correctly.

### CODE REVIEW

**Comment by rsahlstrom** [comment]
@jehoshua02 Thoughts?

**Comment by rsahlstrom** [comment]
Let me add a README.md and push the ghpages example and add a travis ci file.

**Comment by rsahlstrom** [comment]
Review ready to go!

**Comment by jehoshua02** [comment]
I feel bad for shaking things up. I really should have given my input sooner. But I was imagining this for the public interface:

``` javascript
var React = require('react');
var ClassNameMixin = require('class-name-mixin').ClassNameMixin; /* [1] */


var MyComponent = React.createClass({

  mixins: [ClassNameMixin], /* [2] */

  render: function () {
    <div className={this.getClassName()}></div> /* [3] */
  },

  getComponentClasses: function () {
    return classes; /* string or object */
  }
});
```
1. Require and assign the mixin to a local var.
2. Add mixin to the component.
3. Call `this.getClassName()` in the render method. This method is added by the mixin and would always return a string for the `className` prop.
4. Define `getComponentClasses` method for the mixin to call to get the component classes. The method can return string or object and the mixin juggles the two types.

Let me know what you think.

**Comment by rsahlstrom** [comment]
How would you handle code that needed to do something like this:

``` js
render: function() {
  if (this.state.renderAsCollapsible) {
    return this.renderAsCollapsible();
  } else {
    return this.renderAsPanel();
  }
},

renderAsCollapsible: function() {
  return (
    <Collapsible className={this.getCombinedClassNames('ddm-collapsible--panel')}>Collapsible</Collapsible>
  );
}

renderAsPanel: function() {
  return (
    <div className={this.getCombinedClassNames('ddm-panel')}>Panel</div>
  );
}
```

**Comment by jehoshua02** [comment]
For better or worse:

``` javascript
render: function() {
  if (this.state.renderAsCollapsible) {
    return this.renderAsCollapsible();
  } else {
    return this.renderAsPanel();
  }
},

renderAsCollapsible: function() {
  return (
    <Collapsible className={this.getClassName()}>Collapsible</Collapsible>
  );
}

renderAsPanel: function() {
  return (
    <div className={this.getClassName()}>Panel</div>
  );
}

getComponentClasses: function () {
  var classes = {};

  if (this.state.renderAsCollapsible) {
    classes['ddm-collapsible--panel'] = true;
  } else {
    classes['ddm-panel'] = true;
  }

  return classes;
}
```

**Comment by jehoshua02** [comment]
Or:

``` javascript
getComponentClasses: function () {
  return (this.state.renderAsCollapsible) ? 'ddm-collapsible--panel' : 'ddm-panel';
}
```

**Comment by jehoshua02** [comment]
For greater flexibility, I could happily go with something like this:

``` javascript
var React = require('react');
var ClassNameMixin = require('class-name-mixin').ClassNameMixin;


var MyComponent = React.createClass({

  mixins: [ClassNameMixin],

  render: function () {
    var classes = ...; /* string or object */
    <div className={this.getClassName(classes)}></div>
  },

  getComponentClasses: function () {
    var classes = ...; /* string or object */
    return classes;
  }
});
```

**Comment by jehoshua02** [comment]
@janiv I think this is great. Thank you for taking the time to put it together.

**Comment by rsahlstrom** [comment]
I'll merge and tag this once the tests pass since we paired programmed it together and use that as our review.

**Pull request merged**
